# pyproject.toml
[tool.pytest.ini_options]
addopts = "--cov=dynamic_array --cov-report=term-missing"
testpaths = ["tests"]

[tool.hypothesis]
derandomize = true
max_examples = 100

[tool.flake8]
max-line-length = 88
ignore = "E203, W503, E501"
exclude = ["__pycache__", ".git", "venv"]